package com.transit.web_gis.vo;

import lombok.Data;
import lombok.Getter;
import lombok.Setter;

@Data
@Getter
@Setter
public class BmsVo {
    private String station_id;
    private String rowid;
    private String station_nm;
    private String link_id;
    private String station_use_cd;
    private String station_use_nm;
    private String trsf_station_yn;
    private String trsf_station_nm;
    private String ctrd_yn;
    private String ctrd_nm;
    private String station_nm_eng;
    private String ars_id;
    private String org_cd;
    private String gis_yn;
    private String rgtr_id;
    private String reg_dt;
    private String note;
    private String sbrd_type_cd;
    private String sbrd_type_nm;
    private String stdg_cd;
    private String area_cd;
    private String use_yn;
    private String station_nm_chn;
    private String station_nm_jap;
    private String station_nm_vnm;
    private String drt_yn;
    private String node_id;
    private String crossroad_nm;
    private String lat;
    private String lng;
    private Integer link_seq;
    private String addroute_cd;
    private String route_id;
    private Integer station_seq;
    private String route_nm;
    private String comp_id;
    private String comp_nm;
    private String sstn_nm;
    private String estn_nm;
    private String per_org_nm;
    private String run_path;
    private Integer trng_stn_seq;
    private String road_nm;
    private String point_id;
    private String bwod_yn;
    private String cfmtn_dist;
    private String gis_dist;
    private String acmlt_dist;
    private String mdfcn_dt;
    private String work_cd;
    private String proceccing_cd;
    private String hist_id;
    private String begin_lat;
    private String begin_lng;
    private String end_lat;
    private String end_lng;
    private String link_dist;
    private String bgng_node_id;
    private String end_node_id;
    private String svy_dist;
    private String dropgs_cd;
    private String aprv_id;
    private String last_aprv_dt;
    private String mdfr_id;
    private String min_val;
    private String run_tob;
    private String run_tob_nm;
    private String total_run_dist;
    private String dup_dist;
    private String station_show_flag;
    private String station_show_lvl;
    private String station_show_label;
    private String link_show_flag;
    private String link_show_lvl;
    private String link_show_label;
    private String node_show_flag;
    private String node_show_lvl;
    private String node_show_label;
    private String total_run_dist_aba;
    private String run_section_cd;
    private String virtual_id;
    private String veh_no;
    private String run_ymd;
    private String station_type_cd;
    private String station_type_cd_nm;
    private String bit_pr_yn;
    private String bit_type_cd;
    private String bit_type_cd_nm;
    private String bit_instl_yn;
    private String lot_num_addr;
    private String cdnt_x;
    private String cdnt_y;
    private String ride_tns_cnt;
    private String alight_cnt;
    private String bit_type_cd_01;
    private String bit_type_cd_02;
    private String bit_type_cd_03;
    private String bit_type_cd_04;
    private String bit_type_cd_05;
    private String bit_type_cd_06;
}
